# Generated by Django 5.2.5 on 2025-08-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_id', models.CharField(db_index=True, help_text='Tenant/client identifier for multi-tenant scoping', max_length=64)),
                ('provider', models.CharField(choices=[('vapi', 'Vapi'), ('elevenlabs', 'ElevenLabs'), ('azure', 'Azure'), ('aws', 'AWS Polly'), ('google', 'Google')], help_text='Voice provider (openai, elevenlabs, etc.)', max_length=20)),
                ('name', models.CharField(help_text='Display name of the voice', max_length=64)),
                ('voice_id', models.CharField(help_text='Provider-specific voice identifier', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Optional description for the voice')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='voiceconfig',
            name='dashboard_v_client__da272c_idx',
        ),
        migrations.RemoveField(
            model_name='voiceconfig',
            name='provider',
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['provider', 'is_active'], name='dashboard_v_provide_b06d47_idx'),
        ),
        migrations.AddIndex(
            model_name='voice',
            index=models.Index(fields=['client_id', 'provider'], name='dashboard_v_client__e3423b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voice',
            unique_together={('provider', 'voice_id')},
        ),
        migrations.AlterField(
            model_name='voiceconfig',
            name='voice',
            field=models.ForeignKey(blank=True, help_text='Selected voice from available options', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.voice'),
        ),
        migrations.AddIndex(
            model_name='voiceconfig',
            index=models.Index(fields=['client_id'], name='dashboard_v_client__899c86_idx'),
        ),
    ]
