# Generated by Django 5.2.5 on 2025-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='provider',
            field=models.CharField(choices=[('azure_openai', 'Azure OpenAI')], default='azure_openai', max_length=20),
        ),
    ]
