# Generated by Django 5.2.5 on 2025-08-29 14:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_modelconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceconfig',
            name='ambient_sound_enabled',
            field=models.BooleanField(default=False, help_text='Enable ambient background sound'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='ambient_sound_type',
            field=models.CharField(choices=[('none', 'None'), ('office_ambience', 'Office Ambience'), ('custom', 'Custom URL')], default='office_ambience', help_text='Type of ambient sound to play', max_length=20),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='ambient_sound_url',
            field=models.URLField(blank=True, help_text='Custom ambient sound URL'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='ambient_sound_volume',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), help_text='Ambient sound volume (0-100)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='thinking_sound_enabled',
            field=models.BooleanField(default=False, help_text='Enable thinking sound when agent is processing'),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='thinking_sound_primary',
            field=models.CharField(choices=[('none', 'None'), ('keyboard_typing', 'Keyboard Typing'), ('keyboard_typing2', 'Keyboard Typing 2')], default='keyboard_typing', help_text='Primary thinking sound', max_length=20),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='thinking_sound_primary_volume',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.8'), help_text='Primary thinking sound volume (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='thinking_sound_secondary',
            field=models.CharField(choices=[('none', 'None'), ('keyboard_typing', 'Keyboard Typing'), ('keyboard_typing2', 'Keyboard Typing 2')], default='keyboard_typing2', help_text='Secondary thinking sound', max_length=20),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='thinking_sound_secondary_volume',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.7'), help_text='Secondary thinking sound volume (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs')], help_text='Voice provider (openai, elevenlabs, etc.)', max_length=20),
        ),
    ]
