# Generated by Django 5.2.5 on 2025-08-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_audio_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfig',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='temperature',
        ),
    ]
