# Generated by Django 5.2.5 on 2025-08-29 20:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_website_scraping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedconfig',
            name='on_no_punctuation_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='on_number_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='on_punctuation_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='smart_endpointing',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='start_speaking_wait_seconds',
        ),

        migrations.AddField(
            model_name='advancedconfig',
            name='turn_detection_create_response',
            field=models.BooleanField(default=True, help_text='Whether to automatically generate response when VAD stop event occurs'),
        ),
        migrations.AddField(
            model_name='advancedconfig',
            name='turn_detection_interrupt_response',
            field=models.BooleanField(default=True, help_text='Whether to automatically interrupt ongoing response when VAD start event occurs'),
        ),
        migrations.AddField(
            model_name='advancedconfig',
            name='turn_detection_prefix_padding_ms',
            field=models.PositiveIntegerField(default=250, help_text='Amount of audio to include before VAD detected speech (in milliseconds)'),
        ),
        migrations.AddField(
            model_name='advancedconfig',
            name='turn_detection_silence_duration_ms',
            field=models.PositiveIntegerField(default=1500, help_text='Duration of silence to detect speech stop (in milliseconds)'),
        ),
        migrations.AddField(
            model_name='advancedconfig',
            name='turn_detection_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.89'), help_text='Activation threshold for VAD (0.0 to 1.0). Higher threshold requires louder audio.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
