# Generated by Django 5.2.5 on 2025-08-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_replace_speaking_plan_with_turn_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceconfig',
            name='input_min_characters',
        ),
        migrations.RemoveField(
            model_name='voiceconfig',
            name='punctuation_boundaries',
        ),
    ]
