# Generated by Django 4.2.5 on 2025-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='privacyconfig',
            name='dashboard_p_client__7b6d5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='privacyconfig',
            name='dashboard_p_client__92743a_idx',
        ),
        migrations.RemoveField(
            model_name='privacyconfig',
            name='audio_format',
        ),
        migrations.RemoveField(
            model_name='privacyconfig',
            name='auto_delete_recordings',
        ),
        migrations.RemoveField(
            model_name='privacyconfig',
            name='data_retention_days',
        ),
        migrations.RemoveField(
            model_name='privacyconfig',
            name='hipaa_enabled',
        ),
        migrations.RemoveField(
            model_name='privacyconfig',
            name='pci_enabled',
        ),
        migrations.RemoveField(
            model_name='privacyconfig',
            name='video_recording',
        ),
        migrations.AlterField(
            model_name='privacyconfig',
            name='audio_recording',
            field=models.BooleanField(default=True, help_text='Record the conversation with the assistant'),
        ),
        migrations.AddIndex(
            model_name='privacyconfig',
            index=models.Index(fields=['client_id'], name='dashboard_p_client__fcbde8_idx'),
        ),
    ]
