# Generated by Django 4.2.5 on 2025-08-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_simplify_privacy_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedconfig',
            name='idle_timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='keypad_delimiter',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='keypad_input_enabled',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='keypad_timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='max_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='max_idle_messages',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='silence_timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='stop_speaking_backoff_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='stop_speaking_voice_seconds',
        ),
        migrations.RemoveField(
            model_name='advancedconfig',
            name='stop_speaking_words',
        ),
        migrations.DeleteModel(
            name='MessagingConfig',
        ),
    ]
