# Generated by Django 4.2.5 on 2025-08-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_advanced_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedconfig',
            name='voicemail_detection_provider',
        ),
    ]
