# Generated by Django 5.2.5 on 2025-08-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_unused_fields'),
        ('dashboard', '0011_remove_voicemail_detection_provider'),
    ]

    operations = [
    ]
