# Generated by Django 5.2.5 on 2025-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_merge_20250830_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedfunctions',
            name='email_integration',
            field=models.BooleanField(default=False, help_text='Enable email sending capabilities'),
        ),
        migrations.AddField(
            model_name='predefinedfunctions',
            name='sms_integration',
            field=models.BooleanField(default=False, help_text='Enable SMS sending capabilities'),
        ),
    ]
