# Generated by Django 5.2.5 on 2025-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_integration_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedfunctions',
            name='enable_dial_keypad',
        ),
        migrations.RemoveField(
            model_name='predefinedfunctions',
            name='forwarding_country',
        ),
        migrations.RemoveField(
            model_name='predefinedfunctions',
            name='forwarding_number',
        ),
    ]
