# Generated by Django 5.2.5 on 2025-08-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_dial_keypad_and_forwarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsconfig',
            name='min_messages_for_summary',
        ),
        migrations.RemoveField(
            model_name='analyticsconfig',
            name='summary_timeout_sec',
        ),
    ]
