# Generated by Django 5.2.5 on 2025-08-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_success_evaluation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsconfig',
            name='structured_timeout_sec',
        ),
    ]
