# Generated by Django 5.2.5 on 2025-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_structured_timeout_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsconfig',
            name='structured_prompt',
            field=models.TextField(blank=True, default='You will be given a transcript of a call and the system prompt of the AI participant. Extract structured data according to the schema below.', help_text='Prompt for extracting structured data'),
        ),
    ]
