# Generated by Django 4.2.5 on 2025-08-27 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='badge-primary', help_text='daisyUI badge color class', max_length=20)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people_segments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='people_segm_tenant__467fae_idx')],
                'unique_together': {('tenant_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='CRM/HRIS/Bank core ID', max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(blank=True, help_text='Company name for company type', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phones', models.JSONField(blank=True, default=list, help_text='Array of phone numbers in E.164 format')),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, help_text='Company name for person type', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person for company type', max_length=200)),
                ('segments', models.JSONField(blank=True, default=list, help_text='Array of segment IDs')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people_contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'party_type'], name='people_cont_tenant__0de1c0_idx'), models.Index(fields=['tenant_id', 'external_id'], name='people_cont_tenant__b9329d_idx'), models.Index(fields=['tenant_id', 'email'], name='people_cont_tenant__b34a4f_idx')],
            },
        ),
    ]
