# Generated by Django 4.2.5 on 2025-08-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='people_cont_tenant__0de1c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='segment',
            name='people_segm_tenant__467fae_idx',
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='party_type',
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, help_text='Company name', max_length=200),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='segment',
            name='tenant_id',
        ),
    ]
