# Generated by Django 4.2.5 on 2025-08-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_contact_people_cont_tenant__0de1c0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='segment_id',
            field=models.CharField(blank=True, help_text='Optional segment identifier for auto-creation', max_length=100),
        ),
    ]
