# Generated by Django 5.2.5 on 2025-08-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_contact_segment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='segment_id',
        ),
    ]
