# Generated by Django 4.2.5 on 2025-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_contact_segment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='tenant_id',
            field=models.CharField(db_index=True, default='zain_bh', max_length=100),
        ),
    ]
