# Generated by Django 4.2.5 on 2025-08-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phones',
            field=models.JSONField(blank=True, default=list, help_text='Array of phone numbers in E.164 format'),
        ),
    ]
