# Generated by Django 4.2.5 on 2025-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_add_back_phones_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('tenant_id', 'external_id'), name='unique_tenant_external_id'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('tenant_id', 'email'), name='unique_tenant_email'),
        ),
    ]
