# Generated by Django 4.2.5 on 2025-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_convert_phones_to_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('tenant_id', 'phone'), name='unique_tenant_phone'),
        ),
    ]
