# Generated by Django 4.2.5 on 2025-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_add_phone_unique_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant_id', 'phone'], name='people_cont_tenant__2f1bc2_idx'),
        ),
    ]
