# Generated by Django 4.2.5 on 2025-08-26 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('limit_name', models.CharField(max_length=100)),
                ('limit_value', models.PositiveIntegerField()),
                ('current_usage', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'authorization_tenant_limit',
                'indexes': [models.Index(fields=['tenant_id', 'limit_name'], name='authorizati_tenant__f2b17e_idx')],
                'unique_together': {('tenant_id', 'limit_name')},
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('feature_name', models.CharField(max_length=100)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
            options={
                'db_table': 'authorization_tenant_feature_usage',
                'indexes': [models.Index(fields=['tenant_id', 'feature_name'], name='authorizati_tenant__d11b40_idx'), models.Index(fields=['tenant_id', 'period_start'], name='authorizati_tenant__ebe10e_idx')],
                'unique_together': {('tenant_id', 'feature_name', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='TenantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('features_used', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_tenant_session',
                'indexes': [models.Index(fields=['tenant_id', 'started_at'], name='authorizati_tenant__72e162_idx'), models.Index(fields=['tenant_id', 'is_active'], name='authorizati_tenant__4650ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('feature_access', 'Feature Access'), ('data_access', 'Data Access'), ('limit_exceeded', 'Limit Exceeded'), ('plan_change', 'Plan Change'), ('admin_action', 'Admin Action')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(default=dict)),
                ('token_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_tenant_audit_log',
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='authorizati_tenant__92164e_idx'), models.Index(fields=['tenant_id', 'action'], name='authorizati_tenant__010163_idx'), models.Index(fields=['timestamp'], name='authorizati_timesta_fa6a94_idx')],
            },
        ),
    ]
