# Generated by Django 5.2.5 on 2025-08-26 03:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('prompt_template', models.TextField()),
                ('voice_id', models.CharField(blank=True, max_length=100)),
                ('agent_config', models.JSONField(default=dict)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_calls', models.PositiveIntegerField(default=1000)),
                ('max_concurrent', models.PositiveIntegerField(default=10)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('successful_calls', models.PositiveIntegerField(default=0)),
                ('failed_calls', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('call_duration', models.PositiveIntegerField(default=0)),
                ('agent_response', models.TextField(blank=True)),
                ('user_input', models.TextField(blank=True)),
                ('conversation_log', models.JSONField(default=list)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('position', models.PositiveIntegerField()),
                ('is_processing', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='campaigns.campaign')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='campaigns.campaignsession')),
            ],
            options={
                'db_table': 'campaign_queue',
                'ordering': ['-priority', 'position', 'queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant_id', 'status'], name='campaigns_tenant__d8e2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant_id', 'created_at'], name='campaigns_tenant__287dae_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsession',
            index=models.Index(fields=['tenant_id', 'status'], name='campaign_se_tenant__0a1e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsession',
            index=models.Index(fields=['campaign', 'status'], name='campaign_se_campaig_700a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsession',
            index=models.Index(fields=['session_id'], name='campaign_se_session_3b87e0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignqueue',
            index=models.Index(fields=['campaign', 'priority', 'position'], name='campaign_qu_campaig_1e3198_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignqueue',
            index=models.Index(fields=['is_processing', 'scheduled_for'], name='campaign_qu_is_proc_f2604f_idx'),
        ),
    ]
