# Generated by Django 4.2.5 on 2025-08-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_add_structured_prompt_default'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='assistant',
            field=models.ForeignKey(blank=True, help_text='AI Assistant to use for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dashboard.assistant'),
        ),
    ]
