# Generated by Django 5.2.5 on 2025-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contacts',
            field=models.JSONField(default=list, help_text='List of contacts/phone numbers for this campaign'),
        ),
    ]
